### ISSUE TITLE
hmmlearn not found

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#341]
Error when running nosetests:

E./home/mzhong/nilmtk/nilmtk/nilmtk/metergroup.py:76: RuntimeWarning: Building 1 has an empty 'appliances' list.
  .format(building_id.instance), RuntimeWarning)
......E............../home/mzhong/nilmtk/nilmtk/nilmtk/elecmeter.py:115: UserWarning: There is no meter upstream of this meter 'ElecMeterID(instance=1, building=1, dataset='REDD')' because it is a site meter.
  " it is a site meter.".format(self.identifier))
.../home/mzhong/nilmtk/nilmtk/nilmtk/electric.py:565: DeprecationWarning: `available_power_ac_types` is deprecated. Please use `available_ac_types('power')` instead.
  " `available_ac_types('power')` instead.", DeprecationWarning)
/home/mzhong/nilmtk/nilmtk/nilmtk/measurement.py:64: RuntimeWarning: None of the AC types recorded by Mains are present in `available_ac_types`. Will use try using one of ['active', 'apparent', 'reactive'].
  " Will use try using one of {}.".format(AC_TYPES), RuntimeWarning)
.................
======================================================================
ERROR: Failure: ImportError (No module named hmmlearn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/__init__.py", line 2, in <module>
    from .fhmm_exact import FHMM
  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 7, in <module>
    from hmmlearn import hmm
ImportError: No module named hmmlearn

======================================================================
ERROR: Failure: ImportError (No module named hmmlearn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/mzhong/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/mzhong/nilmtk/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 12, in <module>
    from nilmtk.disaggregate import CombinatorialOptimisation
  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/__init__.py", line 2, in <module>
    from .fhmm_exact import FHMM
  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 7, in <module>
    from hmmlearn import hmm
ImportError: No module named hmmlearn

----------------------------------------------------------------------
Ran 43 tests in 25.570s

FAILED (errors=2)
Closing remaining open files:/home/mzhong/nilmtk/nilmtk/data/energy.h5...done

**Comment by oliparson** [comment]
You can try following the installation instructions here:
https://github.com/hmmlearn/hmmlearn

@nipunreddevil is this the best way to install this package?

**Comment by MingjunZhong** [comment]
This has been solved in https://github.com/nilmtk/nilmtk/issues/321

**Comment by nipunreddevil** [comment]
@mridulmalpotra has been working on a conda packager for nilmtk. Should make installing much easier when he is done.

**Comment by saeedaghabozorgi** [comment]
Hi, I have used the latest instruction for installation but I still see the same error.

**Comment by saeedaghabozorgi** [comment]
======================================================================
======================================================================
ERROR: Failure: ImportError (No module named hmmlearn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Saeed/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/Saeed/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/Saeed/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/Saeed/Box Sync/workspace/xxx/nilmtk/nilmtk/disaggregate/__init__.py", line 3, in <module>
    from .fhmm_exact import FHMM
  File "/Users/Saeed/Box Sync/workspace/xxx/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 10, in <module>
    from hmmlearn import hmm
ImportError: No module named hmmlearn

===================================================

**Comment by JackKelly** [comment]
@saeedaghabozorgi I'm afraid that looks like an HMMLearn issue to me so please talk to them for help.  (I wish we could help everyone with all variety of issues but we're extremely constrained in the amount of time we have available, sorry)

**Comment by JoshuaC3** [comment]
I had this issue and solved it with `pip install -U --user hmmlearn`.

**Comment by bashhwu** [comment]
@JoshuaC3 
I have tried the one you have given but it does not work


 Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn

**Comment by JoshuaC3** [comment]
@bashhwu Sorry, I have not looked at this in some time so cannot be of much help.
