### ISSUE TITLE
NILM FHMM training error

### ISSUE THREAD

**Issue by neekeeta** [nilmtk/nilmtk#426]
I tried to implement the code given on https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

and when I reached 

```python
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(top_5_train_elec, sample_period=60)
```

I got error when code reached  `fhmm.train(top_5_train_elec, sample_period=60)` line

The error was as follows:

```
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', 
  appliances=[Appliance(type='fridge', instance=1)])'

Traceback (most recent call last):

  File "<ipython-input-32-8af3dc2b6748>", line 1, in <module>
    fhmm.train(top_5_train_elec, sample_period=60)

  File "c:\users\nikita patel\anaconda\nilmtk\nilmtk\disaggregate\fhmm_exact.py", 
  line 213, in train learnt_model[meter].fit([X])

  File "build\bdist.win-amd64\egg\hmmlearn\base.py", line 400, in fit
    X = check_array(X)

  File "C:\Users\Nikita Patel\Anaconda\lib\site-packages\sklearn\utils\validation.py", 
  line 350, in check_array array.ndim)

ValueError: Found array with dim 3. Expected <= 2
```

**Comment by JackKelly** [comment]
Hi @neekeeta,

I have just tried to run `nilmtk/docs/manual/user_guide/disaggregation_and_metrics.ipynb` and it runs fine on my machine.

Are you running the code exactly as written in `disaggregation_and_metrics.ipynb` or are you setting `top_5_train_elec` to something different?

Also, please can you show us the output of running this code snippet on your machine:

```python
from nilmtk.utils import show_versions
show_versions()
```

**Comment by JackKelly** [comment]
And are you running the latest NILMTK code?

**Comment by neekeeta** [comment]
I was running from this link

https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

Thanks & Regards
Nikita Patel
PhD Student
Department of Electrical Engineering
Indian Institute of Technology Gandhinagar

**Comment by neekeeta** [comment]
This is the output that I got after running the instruction you suggested.


INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_IN

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 3.2.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.1
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
None

Date: 2015-08-25 14:42:32.344000
Platform: Windows-8-6.2.9200
System version: 2.7
nilmtk version: 0.2.0.dev-
nilm_metadata version: 0.2.0.dev-
numpy version: 1.9.2
matplotlib version: 1.4.3
pandas version: 0.16.2
sklearn version: 0.16.1

Thanks & Regards
Nikita Patel
PhD Student
Department of Electrical Engineering
Indian Institute of Technology Gandhinagar

**Comment by JackKelly** [comment]
In which case, I'm afraid I'm not sure I can help because I can't replicate the issue locally.

@nipunreddevil, do you have any thoughts?

**Comment by neekeeta** [comment]
Thanks Jack for help.

Thanks & Regards
Nikita Patel
PhD Student
Department of Electrical Engineering
Indian Institute of Technology Gandhinagar

**Comment by nipunreddevil** [comment]
I think the issue could be with the data set. I think we faced an issue when someone had an incorrect version of the REDD H5. This was primarily due to the faulty server on which REDD was hosted. 

@neekeeta : Can you do the following and tell us what you get?

```
python
top_5_train_elec.plot()
```

Do this before you train.

Also, what is the size of your REDD H5 file? On my system it is 329 MB.

```
▶ ls -lah /data/REDD/redd.h5
-rw-r--r--  1 nipunbatra  staff   329M May 23 12:37 /data/REDD/redd.h5
```

**Comment by neekeeta** [comment]
This is the output for top_5_train_elec.plot()

[image: Inline image 1]

ls -lah H:/REDD Data/redd.h5

Error: Parameter format not correct - "REDD".

This command is giving error but checked the file properties the size is
approx 330 MB.


Thanks & Regards
Nikita Patel
PhD Student
Department of Electrical Engineering
Indian Institute of Technology Gandhinagar

**Comment by nipunreddevil** [comment]
@neekeeta 
I don't see the image. I guess you'll have to upload it from the Github issue queue.

**Comment by JackKelly** [comment]
The size of `redd.h5` on my system:
```bash
dk3810@achillea:/data/REDD/low_freq$ ls -lh redd.h5
-rw-rw-r-- 1 dk3810 dk3810 329M Aug 25 10:03 redd.h5
dk3810@achillea:/data/REDD/low_freq$ ls -l redd.h5
-rw-rw-r-- 1 dk3810 dk3810 344438874 Aug 25 10:03 redd.h5
```

**Comment by neekeeta** [comment]
This is the output for top_5_train_elec.plot()
![fig_top 5](https://cloud.githubusercontent.com/assets/13886041/9465524/f07eec5e-4b4a-11e5-9d21-d6ece8fe32bb.JPG)

**Comment by nipunreddevil** [comment]
@JackKelly: Could this be a Windows/UNix thing? I doubt it would. Do you know if anyone tried this on Windows? I wonder if @gjwo would have a clue? I don't have a Windows machine to test!

@neekeeta : Even I am having a hard time understanding why this issue crops up! You seem to have correct data. Does this error happen across all buildings?

**Comment by JackKelly** [comment]
> @JackKelly: Could this be a Windows/UNix thing?

could be.  I don't have a Windows machine either :(

**Comment by neekeeta** [comment]
I am getting same error for all buildings

**Comment by JackKelly** [comment]
I've just committed some code which adds an assert: `assert X.ndim == 2`.

@neekeeta please can you pull the latest NILMTK code and re-run your code?

**Comment by neekeeta** [comment]
I pulled the latest NILMTK and re-ran the code
I am still having the same error

fhmm.train(top_5_train_elec, sample_period=60)
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-23-8af3dc2b6748>", line 1, in <module>
    fhmm.train(top_5_train_elec, sample_period=60)

  File "c:\users\nikita patel\anaconda\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 210, in train
    learnt_model[meter].fit([X])

  File "build\bdist.win-amd64\egg\hmmlearn\base.py", line 400, in fit
    X = check_array(X)

  File "C:\Users\Nikita Patel\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 350, in check_array
    array.ndim)

ValueError: Found array with dim 3. Expected <= 2

**Comment by JackKelly** [comment]
> I am still having the same error

Hmmm... which version of HMMLearn are you using?   (sorry, `nilmtk.utils.show_versions()` didn't show `hmmlearn` version until just now!)

The NILMTK code is definitely passing in a 2D array to `fit` on line 210.  I'm confused as to why it becomes a 3D array somewhere in HMMLearn.

**Comment by nipunreddevil** [comment]
Does to be doubly sure, @neekeeta can you add a simple print before and after this: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/fhmm_exact.py#L193

Also, you should print the dimension of X in the same code. This file is located in nilmtk/disaggregate

I'm not 100% sure if the new code ran properly!

**Comment by neekeeta** [comment]
@JackKelly 
hmmlearn version: 0.2.0

@nipunreddevil 
I made following changes

        for i, meter in enumerate(metergroup.submeters().meters):
            meter_data = meter.power_series(**load_kwargs).next().dropna()
            X = meter_data.values.reshape((-1, 1))
            print("before")
            print(X.ndim)
            assert X.ndim == 2
            print("after")
            print(X.ndim)
            self.X = X

I added the print command before and after "assert X.ndim == 2"
as before "X = meter_data.values.reshape((-1, 1))" is not defined
and I got following result:

before
2
after
2
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-2-8af3dc2b6748>", line 1, in <module>
    fhmm.train(top_5_train_elec, sample_period=60)

  File "c:\users\nikita patel\anaconda\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 214, in train
    learnt_model[meter].fit([X])

  File "build\bdist.win-amd64\egg\hmmlearn\base.py", line 400, in fit
    X = check_array(X)

  File "C:\Users\Nikita Patel\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 350, in check_array
    array.ndim)

ValueError: Found array with dim 3. Expected <= 2


There it is showing correct dimensions.

**Comment by JackKelly** [comment]
> @JackKelly 
> hmmlearn version: 0.2.0

Aha.  This is a significant difference to my setup.  Maybe try with hmmlearn 0.1.1 (i.e. the release version of hmmlearn rather than the version from git)?

**Comment by neekeeta** [comment]
I extracted it from here
https://github.com/hmmlearn/hmmlearn

**Comment by JackKelly** [comment]
Please remove your existing hmmlearn installation and try re-installing hmmlearn using `pip install hmmlearn`

**Comment by JackKelly** [comment]
@nipunreddevil which version of hmmlearn are you using?  Can you replicate @neekeeta's bug?

**Comment by nipunreddevil** [comment]
I am on 0.1a of Hmmlearn and the example works for me! Man, these hmm learn people changed something!

**Comment by neekeeta** [comment]
pip install hmmlearn

gives me following result

![hmm](https://cloud.githubusercontent.com/assets/13886041/9472079/cdd3ef30-4b70-11e5-82cb-730feb1cc5d2.JPG)

Please suggest from where should I get the older version

**Comment by nipunreddevil** [comment]
Use the following answer from Stack Overflow: http://stackoverflow.com/a/21699307/743775

and clone tag 0.1.1 from hmm learn repo.

Then, you need to run setup.py on it. Didn't know hmmleanr would break things! sorry for the inconvenience.

**Comment by neekeeta** [comment]
Thank you so much for your quick support. Now my code is running properly.

**Comment by JackKelly** [comment]
Ok, great.  Let's leave this issue open for now because we either need to
modify the nilmtk code to handle the new hmmlearn API or change our
installation docs

**Comment by gjwo** [comment]
Sorry I spotted this a bit late, I take it you don't think this is a Windows related issue any more.

**Comment by JackKelly** [comment]
I've changed the installation docs to recommend that folks install hmmlearn from `pip` not from `git` (it's also easier to install using `pip`!).  Once hmmlearn 0.2.0 is released on pypi, we'll probably have to change our code to use the new hmmlearn API (assuming the new API stays).  I'll close this issue for now and open a new one to remind us to check on hmmlearn 0.2.0 when it's released.

**Comment by JackKelly** [comment]
@gjwo Hi!  Don't worry.  As you say, we don't think this is a 'windows vs linux' thing any more :)
