### ISSUE TITLE
Combad dataset is not loading.

### ISSUE THREAD

**Issue by AmanYdv20** [nilmtk/nilmtk#679]
![screenshot from 2018-06-06 12-30-28](https://user-images.githubusercontent.com/30390766/41855707-f10ab55e-78b0-11e8-8417-b5d658f97879.png)

**Comment by PMeira** [comment]
Did you use the [HDF directly](http://combed.github.io/downloads/combed.h5) or the converter with the raw files?

**Comment by PMeira** [comment]
Downloading the HDF file, I found no issues:

```pycon
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nilmtk import DataSet
>>> combed = DataSet('/data/combed.h5')
>>> elevator = combed.buildings[1].elec['elevator']
>>> elevator.available_columns()
[('energy', 'active'), ('power', 'active'), ('current', None)]
>>> df = next(elevator.load())
>>> df.head()
physical_quantity              energy        power   current
type                           active       active
timestamp
2014-06-02 13:26:58+05:30  3496936.75   659.313232  1.628942
2014-06-02 13:27:28+05:30  3496942.00  2436.010254  5.397957
2014-06-02 13:27:58+05:30  3496960.00   671.236877  1.672291
2014-06-02 13:28:28+05:30  3496966.50  3844.417969  7.942322
2014-06-02 13:28:58+05:30  3496979.25   429.423950  1.429770
>>>
```

I'll test the converter and report back.

**Comment by PMeira** [comment]
There was a small issue in the converter (just fixed it in 4fd7e5f), otherwise it's fine. 

@AmanYdv20 Can you provide more information? Especially:

1. Which OS are you using?
2. Which Python version and distribution?
3. Can you provide a full sample so we can reproduce the issue?

**Comment by AmanYdv20** [comment]
@PMeira I used raw data and convert it. I am using ubuntu 18.04 and python 3.6.5 in anaconda.

**Comment by PMeira** [comment]
@AmanYdv20 Thanks, I'll give it a try on Ubuntu. Since you ran the converter, I'd suggest checking the size of the output file (it should be around 21 MB) and whether using the .h5 download from the dataset website works.

**Comment by AmanYdv20** [comment]
@PMeira I think there is some issue with converter. The .h5 dataset fro website is working fine but when I'm trying to convert the raw data, it shows error.

**Comment by PMeira** [comment]
@AmanYdv20 Does it give a "TypeError: Passing a bool..."? If so, that's what I fixed earlier today. Otherwise, it works fine with Pandas 0.22 (recommended in our `environment.yml`) but fails with Pandas 0.23.1 on the third CSV file (on line `total.columns.set_names(LEVEL_NAMES, inplace=True)`).

I'll have to investigate what changed in Pandas that later, probably tomorrow.

**Comment by PMeira** [comment]
@AmanYdv20 The converter issue with Pandas 0.23 should be fixed now, since 3e6810f

**Comment by nipunbatra** [comment]
@AmanYdv20 Does the fix work for you now? If so, please let's close the issue.

**Comment by AmanYdv20** [comment]
@PMeira I think problem of the dataset is not solved because it still making a file of 8.3kb in .h5 version of the combed dataset which gives same error.
`from nilmtk.dataset_converters import convert_combed`
`convert_combed('../combed', 'combed.h5')`
`from nilmtk import DataSet`
`from nilmtk.utils import print_dict`
`combed = DataSet('combed.h5')`
`elec=combed.buildings[1].elec`
`light = elec['light']`
`light.available_columns()` which shows
[('current', None), ('energy', 'active'), ('power', 'active')]
`df = next(light.load())`
`df.head()`
this gives me the error -
"AttributeError                            Traceback (most recent call last)
<ipython-input-22-d8889fc96ee9> in <module>()
----> 1 df = next(light.load())
      2 df.head()

~/Desktop/test_data/nilmtk-master/nilmtk/datastore/hdfdatastore.py in load(self, key, cols, sections, n_look_ahead_rows, chunksize, verbose)
     72             if terms is None:
     73                 section_start_i = 0
---> 74                 section_end_i = self.store.get_storer(key).nrows
     75                 if section_end_i <= 1:
     76                     data = pd.DataFrame()

AttributeError: 'NoneType' object has no attribute 'nrows'"

**Comment by AmanYdv20** [comment]
@PMeira this folder, I downloaded from the combed site and it contains the folder as described in the paper for commercial load disaggregation by Nipun Sir. As-
combed>>iiitd>>folders contain Academic block and Lecture block

**Comment by PMeira** [comment]
@AmanYdv20 OK, so in the previous version of the converter you were expected to point to the `iiitd` folder for it to work, otherwise it would fail silently producing that small .h5 file.

In this...

> Anyway, I just added a check in the converter to report if not files were actually converted, and try to find the input files in the `iiitd` subfolder of the input path. That should make it less error prone.

...I made the converter try appending `iiitd` in the input path just in case people try to point it to the root `combed` folder.

The official `combed.zip` (from `combed.github.io`) does not contain the root `combed` folder, only `iiitd` -- this is probably the source of our confusion.

**Comment by PMeira** [comment]
@AmanYdv20 Most likely something is wrong with your local installation. That line that causes the error in your traceback...

`df = pd.read_csv(filename_attribute, header=True, names=["timestamp", attribute])`

...is different [in the current version](https://github.com/nilmtk/nilmtk/blob/33a7d348fb5c6578de516d32e58dbb9a40a40d7d/nilmtk/dataset_converters/combed/convert_combed.py#L75):

`df = pd.read_csv(filename_attribute, names=["timestamp", attribute])`

Since that was the first thing I updated, you've been using the wrong version. 
Just update and it'll work.

**Comment by AmanYdv20** [comment]
yeah, it is working. Thanks, @PMeira I want to ask one thing that what amount of dataset is required for training of FHMM in terms of days so that it will give more accurate results.

**Comment by PMeira** [comment]
@AmanYdv20 No problem, thanks for reporting back! 
It depends on the dataset, I'd suggest testing with different training windows and calculating some metrics on the results.
